### ISSUE TITLE
Catalog writer blows up when page 2 is being written

### ISSUE THREAD

**Issue by joelverhagen** [emgarten/Sleet#14]
```
Test Name:	Sleet.Test.CatalogTests.CatalogTest_AddPackageAsync_SupportsWritingMultiplePages
Test FullName:	Sleet.Test.CatalogTests.CatalogTest_AddPackageAsync_SupportsWritingMultiplePages
Test Source:	C:\src\git\github.com\joelverhagen\Sleet\test\SleetLib.Tests\CatalogTests.cs : line 224
Test Outcome:	Failed
Test Duration:	0:00:01.832

Result StackTrace:	
at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Sleet.CatalogUtility.UpdatePageIndex(JObject catalogIndexJson, JObject currentPageJson, Guid commitId) in C:\src\git\github.com\joelverhagen\Sleet\src\SleetLib\Utility\CatalogUtility.cs:line 307
   at Sleet.Catalog.<AddCatalogEntry>d__29.MoveNext() in C:\src\git\github.com\joelverhagen\Sleet\src\SleetLib\Services\Catalog.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sleet.Catalog.<AddPackageAsync>d__13.MoveNext() in C:\src\git\github.com\joelverhagen\Sleet\src\SleetLib\Services\Catalog.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sleet.Test.CatalogTests.<CatalogTest_AddPackageAsync_SupportsWritingMultiplePages>d__2.MoveNext() in C:\src\git\github.com\joelverhagen\Sleet\test\SleetLib.Tests\CatalogTests.cs:line 281
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	System.InvalidOperationException : Sequence contains more than one element
```

Test added in PR: https://github.com/emgarten/Sleet/pull/13

**Comment by emgarten** [comment]
Thanks for finding this!

Fixed by @joelverhagen in https://github.com/emgarten/Sleet/commit/dbf8ad8b5aac89893274ea8e43ecf947e4286a87
